//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace plthsEntities.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Assest
    {
        public int assetID { get; set; }
        public string residentBrgy { get; set; }
        public string votersBrgy { get; set; }
        public string specify { get; set; }
        public string typeHouse { get; set; }
        public string typeLand { get; set; }
        public string CR { get; set; }
        public string sourceLight { get; set; }
        public string typeCoocking { get; set; }
        public string sourceWater { get; set; }
        public string landVihicle { get; set; }
        public string seaVihicle { get; set; }
        public string appliances { get; set; }
        public string internetConnection { get; set; }
        public string others { get; set; }
        public Nullable<int> residentID { get; set; }
    }
}
