//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace plthsEntities.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class borrowed
    {
        public int borrowID { get; set; }
        public string borrower { get; set; }
        public int itemid { get; set; }
        public int num_borrowed { get; set; }
    }
}
