//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace plthsEntities.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cedula
    {
        public int ID { get; set; }
        public string surname { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public string citizenship { get; set; }
        public string civil_status { get; set; }
        public string profession { get; set; }
        public Nullable<int> tax_identification_no { get; set; }
        public Nullable<System.DateTime> birth_date { get; set; }
        public string r_height { get; set; }
        public string r_weight { get; set; }
        public string r_signature { get; set; }
    }
}
