//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace plthsEntities.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fishing
    {
        public int fishID { get; set; }
        public string TypeFishing { get; set; }
        public string RegisterNo { get; set; }
        public string FishingStatus { get; set; }
        public string TypeSharing { get; set; }
        public Nullable<int> residentID { get; set; }
    }
}
