//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace plthsEntities.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class frmBlotterReport
    {
        public int BlotterNo { get; set; }
        public string IncidentLocation { get; set; }
        public string IncidentType { get; set; }
        public string DTIncident { get; set; }
        public string DTReported { get; set; }
        public string IncidentNarrative { get; set; }
        public string Complainant { get; set; }
        public string Complained_Resident { get; set; }
        public string StatusC { get; set; }
        public string NickNameC { get; set; }
        public string Citizenshipc { get; set; }
        public string GenderC { get; set; }
        public Nullable<int> AgeC { get; set; }
        public string MobileC { get; set; }
        public string AdressC { get; set; }
        public string NickNameP { get; set; }
        public string CitizenshipP { get; set; }
        public string GenderP { get; set; }
        public Nullable<int> AgeP { get; set; }
        public string MobileP { get; set; }
        public string AdressP { get; set; }
        public string Office_in_Charge { get; set; }
        public Nullable<int> Purok { get; set; }
        public Nullable<System.DateTime> DOB_C { get; set; }
        public Nullable<System.DateTime> DOB_CR { get; set; }
        public string Purok_C { get; set; }
        public string C_fname { get; set; }
        public string C_mname { get; set; }
        public string C_lname { get; set; }
        public string P_fname { get; set; }
        public string P_mname { get; set; }
        public string P_lname { get; set; }
        public string Signature_1 { get; set; }
        public string Signature_2 { get; set; }
        public string blotterStatus { get; set; }
        public string signed { get; set; }
    }
}
