//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace plthsEntities.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Indigency
    {
        public int ID { get; set; }
        public Nullable<int> ResidentID { get; set; }
        public string Purpose { get; set; }
        public Nullable<int> amount { get; set; }
        public string Issuance { get; set; }
        public string date { get; set; }
    }
}
