//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace plthsEntities.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class inventory
    {
        public int itemID { get; set; }
        public string itemName { get; set; }
        public int quantity { get; set; }
        public string itemStatus { get; set; }
        public Nullable<int> borrowed_quan { get; set; }
    }
}
