//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace plthsEntities.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Missing
    {
        public int ID { get; set; }
        public string Firstname { get; set; }
        public string Middlename { get; set; }
        public string Lastname { get; set; }
        public Nullable<int> Age { get; set; }
        public string Gender { get; set; }
        public string Adress { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> DateMissing { get; set; }
        public string DateFound { get; set; }
        public string Status { get; set; }
        public string Image { get; set; }
        public string Reported { get; set; }
        public string Contact_num { get; set; }
        public Nullable<int> ResidentID { get; set; }
    }
}
