//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace plthsEntities.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class plthsEntities : DbContext
    {
        public plthsEntities()
            : base("name=plthsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<account> accounts { get; set; }
        public virtual DbSet<Assest> Assests { get; set; }
        public virtual DbSet<borrowed> borroweds { get; set; }
        public virtual DbSet<business_permit> business_permit { get; set; }
        public virtual DbSet<Cedula> Cedulas { get; set; }
        public virtual DbSet<Clearance> Clearances { get; set; }
        public virtual DbSet<Farm> Farms { get; set; }
        public virtual DbSet<Fishing> Fishings { get; set; }
        public virtual DbSet<frmBlotterReport> frmBlotterReports { get; set; }
        public virtual DbSet<HouseholdMember> HouseholdMembers { get; set; }
        public virtual DbSet<Indigency> Indigencies { get; set; }
        public virtual DbSet<inventory> inventories { get; set; }
        public virtual DbSet<Issued_place> Issued_place { get; set; }
        public virtual DbSet<LiveStock> LiveStocks { get; set; }
        public virtual DbSet<Missing> Missings { get; set; }
        public virtual DbSet<official> officials { get; set; }
        public virtual DbSet<payment> payments { get; set; }
        public virtual DbSet<Purok> Puroks { get; set; }
        public virtual DbSet<request> requests { get; set; }
        public virtual DbSet<Resident> Residents { get; set; }
        public virtual DbSet<service> services { get; set; }
    }
}
