//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace plthsEntities.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purok
    {
        public int Purok_Id { get; set; }
        public string Purok_Nane { get; set; }
        public string Purok_Leader { get; set; }
        public string Contact { get; set; }
        public string pstatus { get; set; }
        public Nullable<int> PurokLeaderID { get; set; }
    }
}
