//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace plthsEntities.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class request
    {
        public int request_id { get; set; }
        public int service_id { get; set; }
        public Nullable<int> res_id { get; set; }
        public string name { get; set; }
        public string isResident { get; set; }
        public System.DateTime dateCreated { get; set; }
        public string printed { get; set; }
        public Nullable<System.DateTime> datePrinted { get; set; }
        public decimal amount { get; set; }
        public int payment_id { get; set; }
    }
}
