//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace plthsEntities.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resident
    {
        public int ID { get; set; }
        public string Lastname { get; set; }
        public string Firstname { get; set; }
        public string Middlename { get; set; }
        public string Gender { get; set; }
        public Nullable<int> Age { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> Birthdate { get; set; }
        public string Religion { get; set; }
        public string Citizenship { get; set; }
        public Nullable<int> PurokID { get; set; }
        public string Adress { get; set; }
        public string Profession { get; set; }
        public string Dialect { get; set; }
        public string civil_status { get; set; }
        public string status { get; set; }
        public string filename { get; set; }
        public string Voter_id { get; set; }
        public string Precint_No { get; set; }
        public string e_attainment { get; set; }
        public string fullname { get; set; }
        public string dataStatus { get; set; }
        public string picture { get; set; }
        public string typeofEmployer { get; set; }
        public string monthlyIncome { get; set; }
        public string otherIncome { get; set; }
        public string philhealth { get; set; }
        public string personType { get; set; }
        public string typeNo { get; set; }
        public string typedateIssued { get; set; }
        public string supportNeed { get; set; }
        public string typeofPension { get; set; }
        public string soloParentNo { get; set; }
        public string BloodType { get; set; }
        public string Occupation { get; set; }
        public string WorkType { get; set; }
        public string Name { get; set; }
        public string midName { get; set; }
        public string Lname { get; set; }
        public Nullable<System.DateTime> dateB { get; set; }
        public string sex { get; set; }
        public string CivilStatus { get; set; }
        public string BloodT { get; set; }
        public string Eattainment { get; set; }
        public string Coursetwo { get; set; }
        public string Occupationtwo { get; set; }
        public string WorkTypetwo { get; set; }
        public string Typeemployertwo { get; set; }
        public string MIncome { get; set; }
        public string Skills { get; set; }
        public string Osi { get; set; }
        public string fourps { get; set; }
        public string combineIncome { get; set; }
    }
}
